<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_selected</name>
   <tag></tag>
   <elementGuidId>231d6a0d-17e3-4d1a-a88a-c82536a804d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div/div[2]/div[2]/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div/div/div[2]/div[2]/p/span</value>
      <webElementGuid>a522b1d3-ba33-437e-94ed-b0dbe3539ae0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
